local loadTips = {}

-- Add loadscreen tips here

loadTips.tipTable = {
	"This was a pain to code :'(",
	"The power of a starman lets you stomp on enemies like normal!",
	"Collect Minus Medals and you might be in for a surprise...",
	"Some goal poles can be jumped over, see what happens if you do!",
	"The Beetroot can defeat enemies that fireballs can't.",
	"Use the Jumping Lui to your advantage. Some ceilings can be jumped over!",
	"Check the credits file to see who made what level!",
	"Not all bonus areas are underground, sometimes a vine can take you to the skies!",
	"Defeat Bowser with fireballs and you might find an imposter!",
	"Keep searching, the end of the game might not be the end of the levels.",
	"Luigi can jump higher, but be careful as he's a lot more slippery!",
	"There might be more characters to unlock than just the Mario Bros.",
	"Hammer Bros. are no joke, it's usually best to just run under them, or bonk them from below.",
	"Cheep Cheeps like to jump out of the water sometimes, so be careful on bridges!",
	"Hit every block you can, you never know what's inside...",
	"Low on lives? 1-UP Mushrooms are often found in hidden nooks.",
	"Did you know these are randomized?",
	"Ever feel stuck? Just walk to the right!",
	"Ever feel stuck? Just walk to the left if you even can!",
	"Kondor Koopas are unused in the original SMB1!",
	"Todd. was. here.",
	"so retro",
	"So Retro.",
	"SO RETRO!",
	"The Rip Lair is a group of random people who do cool (and random) stuff",
	"Beware of strong winds! They can push you off ledges.",
	"Some bloopers can swim without the need of water!",
	"kill everyone",
	"kill everything",
	"If you see a grumpy looking green Toad with a monobrow, say hi!",
	"If you jump 2401 times on the 20th tile in 1-3, you unlock Luigi!",
	"If you jump 6814 times on the 61st tile in 4-2, you unlock Waluigi!",
	"You can use the Beetroot to plow through walls of bricks! Maybe you'll find something special in them...",
	"Ripro is rip + retro.",
	"In bonus rooms, the character head will change depending on your character.",
	"They say there's a castle filled with Bowsers, found in a place unknown...",
	"The timer is much faster than normal (for the sake of accuracy), so... hurry up!",
	"Beyond the goal pole, you might find a mysterious pipe... why don't you enter it?",
	"Hurry! After defeating Lakitu, he may return within a few seconds.",
	"Bewear of poison mushrooms. Their icky taste will make you lose your powerup.",
	"Don't stomp on the Bloopers underwater. You can only stomp on Bloopers that swim in the air.",
	"Throughout your journey, some familiar foes from past adventures may appear...",
	"Get off quick! Standing on lift platforms for too long will cause them to fall!",
	"Heads up! Koopa Troopas can still hurt you for a brief period after bonking them from below.",
	"Larger Goombas will split into two smaller Goombas when stomping on them.",
	"Bowser Jr. is full of surprises. He'll sometimes throw shells or toss hammers just like his dad.",
	"Remember to introduce the first enemy of your level in a safe environment.",
	"The FitnessGram Pacer Test is a multistage aerobic capacity test that progressively gets more difficult as it continues.",
	"Trans rights are human rights!",
	"Bunnings Warehouse",
	"This has become a bit. My sanity has perished. Help me.",
	"Don't give up!",
	"Boom Boom was planned for the episode, but he was ultimately scapped for Junior.",
	"Remember, this is just a game - take a break if you need one.",
	"Fire In The Hole",
	"Onward and upward!",
	"I wonder what Goombas taste like...",
	"Peaches, Peaches, Peaches, Peaches, Peaches, Peaches, Peaches, Peaches, Peaches, Peaches",
	"If Mario, then only Bros!",
	"|: |",
	"Do not use AI for making assets. Don't even try.",
	"Never share your passwords!",
	"written by devious",
	"The Bubble Flower had a bug where the bubbles could consume almost anything. However, this was eventually fixed.",
	"Also check out The Rip Lair's Powerup Pack!",
	"Also check out The Online GFX Pack!",
	"Remember the minus world glitch from the original game?",
	"Donkey Goomba",
	"First, translate devious. to binary, then add all of the binary values together, and you get a Spring Mushroom!",
	"01101110 01100101 01110110 01100101 01110010 00100000 01100111 01101111 01101110 01101110 01100001 00100000 01100111 01101001 01110110 01100101 00100000 01111001 01101111 01110101 00100000 01110101 01110000",
	"Mario Start!",
	"Luigi Start!",
	"Wario Start!?",
	"Look out behind you!",
	"Sorry, no playable cow.",
	"kliklolklilkllklilkloklillkllkilkllokllikllkliklolklilkllklilklolklilkllklilklolklilklklilklolklilklkllikllokllikllklilklolkilkllklilkllolklilklkilklolklilkl"
}

return loadTips